name: skuld
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flame: ^1.20.0
  intl: ^0.19.0
  provider: ^6.1.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5
  jiffy: ^6.3.1
  choice: ^2.3.2
  extended_wrap: ^0.1.5
  shared_preferences: ^2.3.2
  animate_do: ^4.2.0
  drift: ^2.18.0
  drift_flutter: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13
  drift_dev: ^2.18.0

flutter:
  uses-material-design: true
